# Makefile for Ninja dev.

init: ninja-init

ninja-init:
	npm install grpc-web grpc-web-react google-protobuf @types/react @types/react-dom @types/node

# Define phony targets to avoid conflicts with files of the same name & improve performance
.PHONY: init ninja-init
